### ISSUE TITLE
Why is this in two dimensions?

### ISSUE THREAD

**Issue by myk-yogurt** [surya9teja/3D-Artificial-Potential-Field#1]
They wrote it in three dimensions, but when you run it, it's going to be two dimensions, right?

**Comment by surya9teja** [comment]
> They wrote it in three dimensions, but when you run it, it's going to be two dimensions, right?

Not exactly, If you use terrestrial robot 2D navigation is fine but when you aerial robots then you need 3D algorithms to navigate. So, it is based on your application how you want to use.
